### ISSUE TITLE
hmset can't write dict

### ISSUE THREAD

**Issue by sagax** [gahr/retcl#6]
Hi!
I have this code

```tcl
puts "TCL VERSION: $tcl_version"

package require retcl
set retcl_version [package require retcl]
puts "RETCL VERSION: $retcl_version"
retcl create rdb

set result_1 [ rdb -sync hmset foo bar baz ]
set result_2 [ rdb -sync hmset foo bar {some value} ]
set result_3 [ rdb -sync hmset foo {bar {some value}} ]

puts "R1: $result_1"
puts "R2: $result_2"
puts "R3: $result_3"
```

and i can't write dictionary with retcl

this result

```txt
TCL VERSION: 8.6
RETCL VERSION: 0.2.1
R1: OK
R2: OK
R3: ERR wrong number of arguments for 'hmset' command
```
how to write dictionary wih retcl?

**Comment by gahr** [comment]
The error is expected, `HMSET` takes one key and one or more (field, value) pairs.

If your dictionary appears verbatim in your source code, your second command is correct. If your dictionary is in a variable you need to expand it first: `rdb hmset foo {*}$mydict`.

**Comment by sagax** [comment]
with expand - all ok, thanks!

**Comment by gahr** [comment]
You're welcome.
